# Generated by Django 2.2.2 on 2019-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0006_auto_20190610_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(null=True, upload_to='artigos/'),
        ),
    ]
